version: '3.8'

services:
  vulnwebapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./app/public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=development
    restart: unless-stopped

# Run in isolated network — Do not expose to internet
networks:
  default:
    driver: bridge
